version: 2

workflows:
  version: 2
  build:
    jobs:
      - build:
          context: SonarCloud
  release:
    jobs:
      - release:
          context: Bintray
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
  nightly:
    triggers:
      - schedule:
          cron: "14 3 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build:
          context: SonarCloud

jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - restore_cache:
          key: custom-maven-release-strategies-v1-{{ .Branch }}-{{ checksum "pom.xml" }}
      - run:
          name: Prepare build
          command: mvn dependency:go-offline || true
      - save_cache:
          paths:
            - ~/.m2
            - ~/.sonar/cache
          key: custom-maven-release-strategies-v1-{{ .Branch }}-{{ checksum "pom.xml" }}
      - run:
          name: Build software
          command: |
            mvn org.jacoco:jacoco-maven-plugin:prepare-agent verify sonar:sonar
      - run:
          name: Save test results
          command: |
            mkdir -p ~/junit/
            find . -type f -regex ".*/target/surefire-reports/.*xml" -exec cp {} ~/junit/ \;
            find . -type f -regex ".*/target/failsafe-reports/.*xml" -exec cp {} ~/junit/ \;
          when: always
      - store_test_results:
          path: ~/junit

  release:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run:
          name: Build software
          command: |
            mvn deploy