name: CI build

on:
  push:
    branches: [ main ]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Set up JDK
        uses: actions/setup-java@v4.4.0
        with:
          java-version: 11
          distribution: 'adopt'
          check-latest: true

      - name: Set up cache for ~./m2/repository
        uses: actions/cache@v4.1.2
        with:
          path: ~/.m2/repository
          key: custom-maven-release-strategies-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            custom-maven-release-strategies

      - name: Build and test code
        run: mvn -B verify --no-transfer-progress
